routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'users-address');

Route::get('users-address', 'HomeController@index')->name('users-address');

Auth::routes();

Route::resource('address', 'Web\AddressController');

Route::resource('users', 'Web\UseController');

app/Shipping_Address.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Shipping_Address extends Model
{
    protected $fillable = [
        'user_id', 'country', 'city', 'street','street_number', 'postal_Code', 
    ];

    public function user()//una direccion de envio le pertenece a un usuario
	{
		return $this->belongsTo(User::class);
	}
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'full_name','short_name', 'email', 'phone','reference', 'password', 
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function addresses(){// Un usuario tiene n direcciones de envio

        return $this->hasMany(Shipping_Address::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Shipping_Address;

class HomeController extends Controller
{
    
    public function index()
    {
        $addresses = Shipping_Address::orderBy('id', 'DESC')->paginate();
        return view('address', compact('addresses'));
    }
}

app/Http/Controllers/Web/AddressController.php
<?php

namespace App\Http\Controllers\Web;

use Illuminate\Http\Request;
//Validation Request
use App\Http\Requests\AddressStoreRequest;
use App\Http\Requests\AddressUpdateRequest;


use App\Http\Controllers\Controller;
use App\Shipping_Address;

class AddressController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $addresses = Shipping_Address::orderBy('id', 'DESC')->paginate();
        return view('web.address.index', compact('addresses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('web.address.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddressStoreRequest $request)
    {
        $address = Shipping_Address::create($request->all());

        return redirect()->route('address.edit', $address->id)->with('info', 'Direccion creada con éxito');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $address = Shipping_Address::find($id);
        return view('web.address.show', compact('address'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $address = Shipping_Address::find($id);
        return view('web.address.edit', compact('address'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AddressUpdateRequest $request, $id)
    {
        $address = Shipping_Address::find($id);
        $address->fill($request->all())->save();

        return redirect()->route('address.edit', $address->id)->with('info', 'Direccion actualizada con exito');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $address = Shipping_Address::find($id);
        $address->delete();
        return back()->with('info', 'Direccion eliminada con exito');
    }
}

app/Http/Controllers/Web/UseController.php
<?php

namespace App\Http\Controllers\Web;

use Illuminate\Http\Request;
//validation Request
use App\Http\Requests\UsersUpdateRequest;


use App\Http\Controllers\Controller;
Use App\User;

class UseController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('id', 'DESC')->paginate();
        return view('web.users.index', compact('users'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('web.users.show' , compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('web.users.edit' , compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(UsersUpdateRequest $request, $id)
    {
        $user = User::find($id);

        $user->fill($request->all())->save();

        return redirect()->route('users.edit', $user->id)->with('info', 'Usuario: '.$user->short_name.'  actualizado con exito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user_name = $user->short_name;
        $user->delete();
        return back()->with('info', 'Usuario: '.$user_name.' eliminado con exito'); 
    }
}

resources/views/address.blade.php
@extends('layouts.app')

@section('content')
    
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-md-1">
                <div class="card">
                    <h4 class="card-header bg-white">Lista de Direcciones</h4>

                    <div class="card-body">
                        
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col" width="10px">ID</th>
                                    <th scope="col">Pertenece a</th>
                                    <th scope="col">Pais</th>
                                    <th scope="col">Ciudad</th>
                                    <th scope="col">Calle</th>
                                    <th scope="col">Numero de Calle</th>
                                    <th scope="col">Codigo postal</th>
                                </tr>
                            </thead>
                            @foreach ($addresses as $address)
                                <tbody>
                                    <tr>
                                        <th scope="row">{{ $address->id }}</th>
                                        <td>{{ $address->user->short_name }}</td>
                                        <td>{{ $address->country }}</td>
                                        <td>{{ $address->city }}</td>
                                        <td>{{ $address->street }}</td>
                                        <td>{{ $address->street_number }}</td>
                                        <td>{{ $address->postal_Code }}</td>
                                        
                                        
                                    </tr>
                                </tbody>
                            @endforeach
                        </table>
                        <div class="col-md-4 offset-md-4">
                            {{ $addresses->render() }}
                        </div>
                        
                    </div>                      
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/users-address') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">
                        @guest

                        @else
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('address.index') }}">Direcciones de Envio</a>
                            </li>
                            
                        @endguest
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Iniciar Sesion') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Registrarse') }}</a>
                            </li>
                        @else
                        
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('users.index') }}">Usuarios</a>
                            </li>


                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->short_name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('cerrar sesion') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            
            <!--Modulo de mensajes de informacion-->

            @if (session('info'))
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 offset-md-2">
                            <div class="alert alert-success">
                                {{ session('info')}}
                            </div>   
                        </div>
                    </div>
                </div>
            @endif

            <!--Modulo de mensajes de errores-->
            @if (count($errors))
                <div class="container">
                    <div class="row">
                        <div class="col-md-8 offset-md-2">
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>   
                        </div>
                    </div>
                </div>
            @endif

            @yield('content')
            
        </main>
    </div>
</body>
</html>

resources/views/web/address/create.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container">
		<div class="row">
			<div class="col-md-8 offset-md-2">
				<div class="card">
					<h4 class="card-header bg-white">Crear Direccion
						<a href="{{ route('address.index') }}" class="btn btn-primary btn-sm float-right">volver</a>
					</h4>

					<div class="card-body">
						
						<form action="{{ route('address.store') }}" method="POST"> 
							
							@csrf
							<input type="hidden" name="user_id" value="{{ auth()->user()->id }}">

							<div class="form-group">
								<label for="country">Pais</label>
								<input type="text" class="form-control" name="country" value="{{ old('country') }}">
							</div>

							<div class="form-group">
								<label for="city">Ciudad</label>
								<input type="text" class="form-control" name="city" value="{{ old('city') }}">
							</div>

							<div class="form-group">
								<label for="street">Calle</label>
								<input type="text" class="form-control" name="street" value="{{ old('street') }}">
							</div>

							<div class="form-group">
								<label for="street_number">Numero de Calle</label>
								<input type="text" class="form-control" name="street_number" value="{{ old('street_number') }}">
							</div>

							<div class="form-group">
								<label for="postal_Code">Codigo postal</label>
								<input type="text" class="form-control" name="postal_Code" value="{{ old('postal_Code') }}">
							</div>

							<br>
							
							<div class="form-group">
								<button type="submit" class="btn btn-sm btn-primary ">
									Guardar
								</button>
							</div>

						</form>
						
					</div>						
				</div>
			</div>
		</div>
	</div>



@endsection

resources/views/web/address/edit.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container">
		<div class="row">
			<div class="col-md-8 offset-md-2">
				<div class="card">
					<h4 class="card-header bg-white">Editar Direccion
						<a href="{{ route('address.index') }}" class="btn btn-primary btn-sm float-right">volver</a>
					</h4>

					<div class="card-body">
						
						<form action="{{ route('address.update',  $address->id) }}" method="POST"> 
							
							@csrf
							@method('PUT')

							<input type="hidden" name="user_id" value="{{ auth()->user()->id }}">

							<div class="form-group">
								<label for="country">Pais</label>
								<input type="text" class="form-control" name="country" value="{{ $address->country }}">
							</div>

							<div class="form-group">
								<label for="city">Ciudad</label>
								<input type="text" class="form-control" name="city" value="{{ $address->city }}">
							</div>

							<div class="form-group">
								<label for="street">Calle</label>
								<input type="text" class="form-control" name="street" value="{{ $address->street }}">
							</div>

							<div class="form-group">
								<label for="street_number">Numero de Calle</label>
								<input type="text" class="form-control" name="street_number" value="{{ $address->street_number }}">
							</div>

							<div class="form-group">
								<label for="postal_Code">Codigo postal</label>
								<input type="text" class="form-control" name="postal_Code" value="{{ $address->postal_Code }}">
							</div>

							<br>
							
							<div class="form-group">
								<button type="submit" class="btn btn-sm btn-primary ">
									Guardar
								</button>
							</div>

						</form>
						
					</div>						
				</div>
			</div>
		</div>
	</div>



@endsection

resources/views/web/address/index.blade.php
@extends('layouts.app')

@section('content')
    
    <div class="container">
        <div class="row">
            <div class="col-md-10 offset-md-1">
                <div class="card">
                    <h4 class="card-header bg-white">Lista de Direcciones
                        <a href="{{ route('address.create') }}" class="btn btn-primary btn-sm float-right">Crear</a>
                    </h4>

                    <div class="card-body">
                        
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col" width="10px">ID</th>
                                    <th scope="col">Pertenece a</th>
                                    <th scope="col">Pais</th>
                                    <th scope="col">Ciudad</th>
                                    <th scope="col">Codigo postal</th>
                                    <th scope="col" colspan="3" class="text-center">Operaciones</th>
                                </tr>
                            </thead>
                            @foreach ($addresses as $address)
                                <tbody>
                                    <tr>
                                        <th scope="row">{{ $address->id }}</th>
                                        <td>{{ $address->user->short_name }}</td>
                                        <td>{{ $address->country }}</td>
                                        <td>{{ $address->city }}</td>
                                        <td>{{ $address->postal_Code }}</td>
                                        
                                        <td width="10px">
                                            <a href="{{ route('address.show', $address->id) }}" class="btn btn-sm btn-primary">Ver</a>
                                        </td>
                                        <td width="10px">
                                            <a href="{{ route('address.edit', $address->id) }}" class="btn btn-sm btn-warning">Editar</a>
                                        </td>
                                        <td width="10px">

                                            <form action="{{ route('address.destroy', $address->id) }}" method="POST">
                                                    @method('DELETE')
                                                    @csrf
                                                    <button type="submit" class="btn btn-sm btn-danger">
                                                        Eliminar
                                                    </button> 
                                            </form> 
                                            
                                        </td>
                                    </tr>
                                </tbody>
                            @endforeach
                        </table>
                        <div class="col-md-4 offset-md-4">
                            {{ $addresses->render() }}
                        </div>
                        
                    </div>                      
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/web/address/show.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container">
		<div class="row">
			<div class="col-md-10 offset-md-1">
				<div class="card">
					<h4 class="card-header bg-white">Visualizar Direccion
						<a href="{{ route('address.index') }}" class="btn btn-primary btn-sm float-right">volver</a>
					</h4>

					<div class="card-body">
						<table class="table">
							<thead>
								<tr>
									<th scope="col" width="10px">ID</th>
									<th scope="col">Pertenece a</th>
									<th scope="col">Pais</th>
									<th scope="col">Ciudad</th>
									<th scope="col">Calle</th>
									<th scope="col">Numero de Calle</th>
									<th scope="col">Codigo Postal</th>
								</tr>
							</thead>

							<tbody>
								<tr>
									<th scope="row">{{ $address->id }}</th>
									<td>{{ $address->user->short_name }}</td>
									<td>{{ $address->country }}</td>
									<td>{{ $address->city }}</td>
									<td>{{ $address->street }}</td>
									<td>{{ $address->street_number }}</td>
									<td>{{ $address->postal_Code }}</td>
								</tr>
							</tbody>
						</table>
					</div>						
				</div>
			</div>
		</div>
	</div>

@endsection

resources/views/web/users/edit.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container">
		<div class="row">
			<div class="col-md-8 offset-md-2">
				<div class="card">
					<h4 class="card-header bg-white">Editar Usuario
						<a href="{{ route('users.index') }}" class="btn btn-primary btn-sm float-right">volver</a>
					</h4>

					<div class="card-body">
						
						<form action="{{ route('users.update', $user->id) }}" method="POST">
							@csrf
							@method('PUT')

							<div class="form-group">
								<label for="full_name">Nombre Completo</label>
								<input type="text" class="form-control" name="full_name" id="full_name"  autofocus value="{{ $user->full_name }}">
							</div>

							<div class="form-group">
								<label for="short_name">Nombre Corto</label>
								<input type="text" class="form-control" name="short_name" id="short_name" value="{{ $user->short_name }}">
							</div>

							<div class="form-group">
								<label for="email">Email</label>
								<input type="email" class="form-control" name="email" value="{{ $user->email }}">
							</div>

							<div class="form-group">
								<label for="phone">Telefono</label>
								<input type="text" class="form-control" name="phone" value="{{ $user->phone }}">
							</div>

							<div class="form-group">
								<label for="reference">Donde nos conocio</label>
								<input type="text" class="form-control" name="reference" value="{{ $user->reference }}">
							</div>

							<br>

							<div class="form-group">
								<button type="submit" class="btn btn-sm btn-primary ">
									Guardar
								</button>
							</div>

						</form>
						
					</div>						
				</div>
			</div>
		</div>
	</div>



@endsection

resources/views/web/users/index.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container">
		<div class="row">
			<div class="col-md-8 offset-md-2">
				<div class="card">
					<h4 class="card-header bg-white">Lista de Usuarios
						<a href="{{ route('address.index') }}" class="btn btn-primary btn-sm float-right">Volver a Direcciones</a>
					</h4>

					<div class="card-body">
						
						<table class="table">
							<thead>
								<tr>
									<th scope="col" width="10px">ID</th>
									<th scope="col">Nombre Corto</th>
									<th scope="col">Email</th>
									<th scope="col" colspan="3" class="text-center">Operaciones</th>
								</tr>
							</thead>
							@foreach ($users as $user)
								<tbody>
									<tr>
										<th scope="row">{{ $user->id }}</th>
										<td>{{ $user->short_name }}</td>
										<td>{{ $user->email }}</td>
										<td width="10px">
											<a href="{{ route('users.show', $user->id) }}" class="btn btn-sm btn-primary">Ver</a>
										</td>
										<td width="10px">
											<a href="{{ route('users.edit', $user->id) }}" class="btn btn-sm btn-warning">Editar</a>
										</td>
										<td width="10px">

											<form action="{{ route('users.destroy', $user->id) }}" method="POST">
													@method('DELETE')
													@csrf
													<button type="submit" class="btn btn-sm btn-danger">
														Eliminar
													</button> 
											</form> 
											
										</td>
									</tr>
								</tbody>
							@endforeach
						</table>
						<div class="col-md-4 offset-md-4">
							{{ $users->render() }}
						</div>
						
					</div>						
				</div>
			</div>
		</div>
	</div>

@endsection

resources/views/web/users/show.blade.php
@extends('layouts.app')

@section('content')
	
	<div class="container">
		<div class="row">
			<div class="col-md-10 offset-md-1">
				<div class="card">
					<h4 class="card-header bg-white">Visualizar Usuario
						<a href="{{ route('users.index') }}" class="btn btn-primary btn-sm float-right">volver</a>
					</h4>

					<div class="card-body">
						<table class="table">
							<thead>
								<tr>
									<th scope="col" width="10px">ID</th>
									<th scope="col">Nombre Completo</th>
									<th scope="col">Nombre Corto</th>
									<th scope="col">email</th>
									<th scope="col">Telefono</th>
									<th scope="col">Donde nos Conocio</th>
								</tr>
							</thead>

							<tbody>
								<tr>
									<th scope="row">{{ $user->id }}</th>
									<td>{{ $user->full_name }}</td>
									<td>{{ $user->short_name }}</td>
									<td>{{ $user->email }}</td>
									<td>{{ $user->phone }}</td>
									<td>{{ $user->reference }}</td>
								</tr>
							</tbody>
						</table>
					</div>						
				</div>
			</div>
		</div>
	</div>

@endsection